### ISSUE TITLE
Implement CRUD API

### ISSUE THREAD

**Issue by mohannadhanafi** [FACG5/BounceBack#104]
Relates to #155 
### GET
- [x] /login
- [x] /logout
- [x] /overview
- [x] /participants
- [x] /participant/:id
- [x] /participant/:id/dates
- [x]  /participant/:id/date/:id
- [x] /participant/:id/courses
- [x]  /participant/:id/course/:id
- [x] /courses
- [x] /course/:id
- [x] /managers
- [x] /manager/:id
- [x] /workers
- [x] /worker/:id

### POST
- [x] /participants/search/name
- [x] /participants/search/date
- [x] /managers/search
- [x] /courses/search
- [x] /workers/search
- [x] /participant
- [x] /participant/:id/date
- [x] /participant/:id/course
- [x] /participant/:id/prison
- [x] /course
- [x] /manager
- [x] /worker

### PUT
- [x] /participant/:id
- [ ] /participant/:id/date/:id
- [ ] /participant/:id/course/:id
- [x] /course/:id
- [x] /manager/:id
- [x] /worker/:id
### DELETE
- [x] /participant
- [x]  /date
- [x]  /training
- [x] /course
- [x] /manager
- [x] /worker
