### ISSUE TITLE
Handle Errors

### ISSUE THREAD

**Issue by knanahassouna1** [FACG5/BounceBack#146]
Relates to #155 
Any function in the web site must be handled for errors

**- Acceptance Criteria:**
### back-end:

- [x] DB participants, managers, worker and courses schema require to it: all required data.
- [x]  If there is an error in the receive response 500 error page will rendered .
- [x]  If there is no response  500 error page will rendered  .
- [x]  If there is a wrong response  500 error page will rendered  .
- [x]  If there is no error in the receive response the page that view it will appear .

### front-end:
- [x]  If there is an error action from client failed message will appear .
- [x]  If there is no rout to view  404 error page will rendered  .
- [x]  If there is no data to view  failed message will appear .
