### ISSUE TITLE
React Routs

### ISSUE THREAD

**Issue by AsalaKM** [FACG5/BounceBack#16]
**Our routs on the website**
- [x] __/login
- [x] __/
- [x] __/participants/add
- [x] __/participants/view
- [x] __/participant/details
- [x] __/participants/prison
- [x] __/participants/courses
- [x] __/participants/course/add
- [x] __/participants/course/details
- [x] __/participants/dates
- [x] __/participants/date/add
- [x] __/participants/date/details
- [x] __/courses/view
- [x] __/courses/details
- [x] __/courses/add
- [x] __/managers/view
- [x] __/manager/details
- [x] __/managers/add
- [x] __/workers/view
- [x] __/worker/details
- [x] __/workers/add
- [x] __/report
- [x] __/report/result
